on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sonarscanner for dotnet
      uses: sonarsource/sonarcloud-github-action@master
      with:
        buildCommand: dotnet build .
        testCommand: dotnet test .
        projectKey: abhithakre_DotNetAPi
        projectName: abhithakre
        sonarOrganisation: abhithakre
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
            /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
